## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

 Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 0

If students address the detailed feedback in a future checkpoint they will earn these points back






|                                  | **Unsatisfactory**                                                                                                                                                                                                                                                                                                                        | **Developing**                                                                                                                                                                                                       | **Proficient**                                                                                                                                                                                            | **Excellent**                                                                                                                                                                            |
|----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **EDA relevance**                | EDA is mostly neither relevant to the question nor helpful in figuring out how to address the question. Or the EDA does address the question, but many obviously relevant variables / analyses / figures were not included. | EDA is partly irrelevant/unhelpful. EDA missed one or two obvioulsy relevant analysis (distributions of single variables or relationships between variables) | EDA includes the obviously relevant / helpful variables in addressing the question.                                                              | Thorough EDA fully explored the dataset                                                                                                                 |
| **EDA analysis and description** | Many of the analyses are poor choices (e.g., using means instead of medians for obviously skewed data), or are poorly described in the text, or do not aid understanding the data                                                                                                                                                     | Some of the analyses are poor choices, or are poorly described in the text, or do not aid understanding the data                                                                                                 | All analyses are correct choices. Only one or two have minor issues in the text descriptions supporting them. Mostly they fit well with other elements of the EDA and support understanding the data  | All analyses are correct choices with clear text descriptions supporting them. The figures fit well with the other elements of the EDA, producing a clear understanding of the data. |
| **EDA figures**                  | Many of the figures are poor plot choices (e.g., using a bar plot to represent a time series where it would be better to use a line plot) or have poor aesthetics (including colormap, data point shape/color, axis labels, titles, annotations, text legibility) or do not aid understanding the data                                | Some of the figures are poor plot choices or have poor aesthetics. Some figures do not aid understanding the data                                                                                                | All figures are correct plot choices. Only one or two have minor questionable aesthetic choices. The figures mostly fit well with the other elements of the EDA and support understanding the data    | All figures are correct plot choices with beautiful aesthetics. The figures fit well with the other elements of the EDA, producing a clear understanding of the data.                |

# COGS 108 - EDA Checkpoint

## Authors

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

## Authors

- Gianncarlo Sanchez: Background Research, Writing-original draft, reviewing/editing, Data wrangling and importing (Billboard data), and methodology 
- Marisol Rodriguez: Background Research, Writing-original draft, reviewing/editing, Data wrangling (Spotify Data), and methodology
- Muhammad Kaaki:
- Ray Santiago: Background Research, Writing-original draft, reviewing/editing, Spotify API and wrangling, and methodology

# Research Question

How do the seasons of the year impact the type of music that appears on Billboard top 100 songs weekly in terms of valence, tempo, and energy, and how do these features compare to one another on a seasonal basis?

## Background and Prior Work

Music is grounded in *a priori* structures of human experience, so it goes. In essence, music is one of the most universal and accessible ways humans, and societies as a whole, encounter emotion and being. As Tomas Clifton describes in their work *Music and the a Priori*, musical experience contains its own form of understanding that is **immediately given** while listening<a name="cite_ref-1"></a>[<sup>1</sup>](#cite_note-1). These structuures are given in forms such as temporal flow, tension, and expectation, which are conditions of our existing in the world; They are not learned. It is because of this that we can call music a type of emotional landcape- A landscape that reveals how we experience and inhabit time, how we move through feeling, and how our inner states are susceptible to shift moment to moment, song-to-song. 

This persnal and deep connection between human emotion and music could offer an explanation for why some songs are described as energetic, uplifting, depressing, or calming<a name="cite_ref-2"></a>[<sup>2</sup>](#cite_note-2). This account ***humanizes*** these labels, reflecting on how the music resonates with our own experiental structures, rather than seeming correlational and abstract. For example, faster tempos tend to evoke feelings of being upbeat or energetic while slower tempos can feel more calming or melancholic. Additionally, valence could lead us to label a song as either sad or happy, seemingly from our own intuition. Clifton's paper helps explain this intuitiveness, where music is directly tied to emotional meaning through structures that shape our experience of the world. 

The major point that our research project aims to address is the fact that emotional experience does not stay constant throughout the year. In the past couple decades, we have better come to understand environmental psychology by studying how seasonal changes in daylight, temperature, and daily routines can influence mood and motivation. The most obvious example of this comes from the term **winter depression**, a.k.a. Seasonal Affective Disorder. 

As Yale School of Medicine describes, SAD is characterized by dperessed mood, decreased enjoyment of activities, sadness, poor energy, and decreased confidence. Most importantly for our research question, through questionaires they note that roughly 90% of people claim to report changes in energy, modd, sleep, and apetite in the winter<a name="cite_ref-3"></a>[<sup>3</sup>](#cite_note-3). This pattern typically starts in fall, seemingly creating a pattern of a rise and decline of mood and emotion that mimicks the dynamics of music itself with the cycles of intensity, valence, and tone that rise and fall over time. 

**Pettijohn et al. (2010) Music for the Seasons: Seasonal Music Preferences in College Students** is a central piece of prior work that directly links seasons to musical preference. In their paper, they describe two studies with undergraduate participants, where students were primed to have different seasons in mind. In the first study, they used a winter vs. summer reading scenario, and in the second they had students write about their own fall, winter, spring, or summer experiences. They then reported their preffered types of music, where the results supported the researchers' hypotheses that seasonal context would shift preferences toward reflexive and complex music in fall and winter, and toward energetic and upbeat music for spring and summer<a name="cite_ref-4"></a>[<sup>4</sup>](#cite_note-4). This paper provides a strong foundation for investigating whether large-scale music trends from the Billboard Top100 also follow this shift from across different seasons. 

There is, however, some opposition to this theory. **Winthorst et al. (2020) Seasonality of mood and affect in a large general population sample** is a clear counter example to our premise- that seasons influence mood. The researchers studied mood and emotional well-being in adults to see if there were real differences in mood across the seasons. They measured positive and negative affect and depressive symptoms using questionaires. They found that season-to-season differences were very small and the evidence was not strong enough to say that seasons dramatically change mood for the great majority of people. The only meaningful effect was due to the personality trait neuroticism, but with only modest effects<a name="cite_ref-5"></a>[<sup>5</sup>](#cite_note-5). This, very clearly, seems to contradict our earlier claim on which we based our research project. While we cannot directly test to confirm or reject their findings, if our results yield a difference of audio features that simmilarly match the findings of Pettijohn et al. (2010), then we may be able to assume some relationship between the two. 

References: 
1. <a name="cite_note-1"></a> [^](#cite_ref-1) Clifton, Thomas. “Music and the a Priori.” Journal of Music Theory 17, no. 1 (1973): 66–85. https://doi.org/10.2307/843118. 
2. <a name="cite_note-2"></a> [^](#cite_ref-2) Silviya Y. 2024. “The Psychology of Music: How Different Genres Affect Mood and Emotions.” HOME. Indigo Music. September 17, 2024. https://indigomusic.com/feature/the-psychology-of-music-how-different-genres-affect-mood-and-emotions.
3. <a name="cite_note-3"></a> [^](#cite_ref-3) “Winter Depression Research Clinic.” 2025. Psychiatry. 2025. https://medicine.yale.edu/psychiatry/research/clinics-and-programs/winter-depression/.
4. <a name="cite_note-4"></a> [^](#cite_ref-4) Pettijohn, T.F., Williams, G.M. & Carter, T.C. Music for the Seasons: Seasonal Music Preferences in College Students. Curr Psychol 29, 328–345 (2010). https://doi.org/10.1007/s12144-010-9092-8
5. <a name="cite_note-5"></a> [^](#cite_ref-5) Winthorst, Wim H et al. “Seasonality of mood and affect in a large general population sample.” PloS one vol. 15,9 e0239033. September 14, 2020. doi:10.1371/journal.pone.0239033

# Hypothesis

We expect a moderate correlation between music preferences and seasonal mood variation. As people's mood and energy change with the seasons, they often choose music that matches how they feel or helps manage their emotions. As a result, music listened to in winter (when moods are generally lower) tends to have lower tempo, valence, and energy, while music listened to in the summer (when moods are higher) tends to be more energetic, have a higher tempo, and higher valence.

## Data

### Data overview

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your data checkpoint feedback

In [2]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/mhollingshead/billboard-hot-100/main/all.json', 'filename':'billboard_all.json'},
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress:   0%|          | 0/1 [00:00<?, ?it/s]
Downloading billboard_all.json:   0%|          | 0.00/4.13M [00:00<?, ?B/s]
Downloading billboard_all.json: 12.3MB [00:00, 123MB/s]
Downloading billboard_all.json: 25.1MB [00:00, 126MB/s]
Downloading billboard_all.json: 37.7MB [00:00, 123MB/s]
Overall Download Progress: 100%|██████████| 1/1 [00:02<00:00,  2.85s/it]

Successfully downloaded: billboard_all.json

### Dataset #1: Billboard Hot 100 (2020–2025 Subset)
Dataset Name: Billboard Hot 100 Complete Chart History
Link to Dataset: https://github.com/mhollingshead/billboard-hot-100
Number of Variables: 7

This dataset originally contains weekly Billboard Hot 100 rankings from 1958 to the present. For this project, the dataset was filtered to include only data from 2020–2025 in order to focus on modern music trends in the streaming era.

Each observation represents one song on the Billboard Hot 100 chart for a specific week.

The most relevant variables include:

song – The name of the song.
artist – The performing artist.
date – The chart week date.
this_week – The song’s rank that week (1–100).
last_week – The song’s previous week rank.
peak_position – The highest rank the song has reached.
weeks_on_chart – Total weeks the song has appeared on the chart.

Chart position is measured from 1 to 100, where 1 indicates the most popular song that week.

One limitation of this dataset is that it does not include musical audio features such as tempo (beats per minute), energy, loudness (decibels), danceability, or valence (musical positivity). Because of this, it may need to be combined with a dataset such as Spotify audio features to analyze musical characteristics. Additionally, differences in how artist names are formatted (for example, featured artists) may make merging datasets more challenging.

In [4]:
## CODE TO LOAD THE DATA
import json
import pandas as pd

with open('data/00-raw/billboard_all.json') as f:
    data = json.load(f)

rows = []

for chart in data:
    chart_date = chart["date"]
    for song in chart["data"]:
        song["date"] = chart_date
        rows.append(song)

billboard_df = pd.DataFrame(rows)

In [5]:
billboard_df["date"] = pd.to_datetime(billboard_df["date"])

##Filter for years 2020–2025
billboard_df = billboard_df[
    (billboard_df["date"].dt.year >= 2020) &
    (billboard_df["date"].dt.year <= 2025)
]

billboard_df.shape

(31300, 7)

In [6]:
billboard_df.shape
billboard_df.head()

,song,artist,this_week,last_week,peak_position,weeks_on_chart,date
320387,All I Want For Christmas Is You,Mariah Carey,1,1.0,1,37,2020-01-04
320388,Rockin' Around The Christmas Tree,Brenda Lee,2,2.0,2,32,2020-01-04
320389,Jingle Bell Rock,Bobby Helms,3,9.0,3,30,2020-01-04
320390,A Holly Jolly Christmas,Burl Ives,4,6.0,4,15,2020-01-04
320391,Circles,Post Malone,5,3.0,1,17,2020-01-04

In [7]:
billboard_df.isnull().sum()

song                 0
artist               0
this_week            0
last_week         4888
peak_position        0
weeks_on_chart       0
date                 0
dtype: int64

In [8]:
def get_season(date):
    month = date.month
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Fall"

billboard_df["season"] = billboard_df["date"].apply(get_season)

billboard_df.head()

,song,artist,this_week,last_week,peak_position,weeks_on_chart,date,season
320387,All I Want For Christmas Is You,Mariah Carey,1,1.0,1,37,2020-01-04,Winter
320388,Rockin' Around The Christmas Tree,Brenda Lee,2,2.0,2,32,2020-01-04,Winter
320389,Jingle Bell Rock,Bobby Helms,3,9.0,3,30,2020-01-04,Winter
320390,A Holly Jolly Christmas,Burl Ives,4,6.0,4,15,2020-01-04,Winter
320391,Circles,Post Malone,5,3.0,1,17,2020-01-04,Winter

In [9]:
billboard_df.to_csv("data/02-processed/billboard_2020_2025_cleaned.csv", index=False)

### Dataset #2: Spotify Song Features from API Code
**Dataset Description**

The Spotify audio features dataset provides a matching set of quantitative measurements that describe the musical and acoustic properties of unique tracks. These features are produced by Spotify's internal data and algorithmic analysis to extract standardized metrics. For this project, our primary focus in three variables- valence, energy, and tempo- which captures different dimensions of musical expression. 

Valence and Energy are unitless scores ranging from 0.0 to 1.0, where valence represents the "positivity" of a track and energy measures intesnity and activity level of the track. Songs with high valence will sound happy and/or cheerful, while high-energy songs will feel loud, fast, and dynamic. Tempo is measured in units of beats oer minute (BPM) and reflects the speed of the underlying beat. Together, these metrics will allow us to quanitify emotional and structural aspects of music across different seasons. 

Although valence, energy, and tempo are the core features for this project, Spotify offers a wide range of additional metrics like danceability, loudness, mode, speechiness, acousticness, etc. These features are not used directly in the project analysis, but are part of the audio features that will be extracted.

**Dataset Concerns and Limitations**

There are key limitations that must be considered when working with this type of data. First is the software aspect through API rate limits. Spotify restricts the number of requests per second which can delay or block data collection. Additionally, we have proxy limitations of this data, where valence and energy are algorithmic estimates, not direct measurements of human emotions.

We first we must create a unique-song artist pairs dataset to ensure the API does not double count.

In [10]:
unique_tracks = billboard_df[['song', 'artist']].drop_duplicates()


We then load Spotify API credentials from an anaconda environment. These IDs are obtained from Spotify Developer platform, where an app was created specifically to pull song data. After retrieving the client and secret codes from the environment, we have to encode the credentials and request an access token from spotify. To do this, we combine the client ID and secret, we encode them in base64, as required by Spotify, and then the code sends a POST request to Spotify's token endpoint.

In [13]:
import requests
import os
import urllib
import time
import base64
from tqdm import tqdm
#for now we use these if jupyter not started from local machine (anaconda) 
client_id = "6ac8d9c25e16499b9882d5002ec10e79"
client_secret = "43ac1d5d81484b119d274bae7a1065db"
#client_id = os.getenv("SPOTIFY_CLIENT_ID")
#client_secret = os.getenv("SPOTIFY_CLIENT_SECRET")

auth_str = f"{client_id}:{client_secret}"
b64_auth_str = base64.b64encode(auth_str.encode()).decode()

token_url = "https://accounts.spotify.com/api/token"
headers_auth = {
    "Authorization": f"Basic {b64_auth_str}",
    "Content-Type": "application/x-www-form-urlencoded"
}
data = {"grant_type": "client_credentials"}

response = requests.post(token_url, headers=headers_auth, data=data)
print(response.json())

access_token = response.json()["access_token"]

{'access_token': 'BQC4VjPFYT3UqQtIp0smwWHkzcBN0BJUkM9xazViLg4-Eu5uk5c8yG_nr9VBWn3nB7p9W_Me5zjPVaA5VJstN_WoRjdQCeaxzKBPLcUmz3MQ1Tk7Pgv8dW2UKjFEaOZ8e0wfiKCqIMI', 'token_type': 'Bearer', 'expires_in': 3600}

Now, we prepare an authorization header for Spotify and define a function to search for Spotify track IDs. We extract these ID's to add them to the unique_tracks dataframe.

In [17]:
if os.path.exists(CACHE_FILE):
    with open(CACHE_FILE, "r") as f:
        cache = json.load(f)
else:
    cache = {}

print(f"Cache loaded: {len(cache)} tracks")

Cache loaded: 1403 tracks

In [ ]:
headers    = {"Authorization": f"Bearer {access_token}"}
CACHE_FILE = "spotify_id_cache.json"

if os.path.exists(CACHE_FILE):
    with open(CACHE_FILE, "r") as f:
        cache = json.load(f)
else:
    cache = {}

def search_track_id(song, artist):
    key = f"{song}|||{artist}"

    if key in cache:
        return cache[key]

    query    = urllib.parse.quote(f"track:{song} artist:{artist}")
    url      = f"https://api.spotify.com/v1/search?q={query}&type=track&limit=1"
    wait     = 2  # initial back-off

    while True:
        response = requests.get(url, headers=headers)

        if response.status_code == 429:
            retry_after = int(response.headers.get("Retry-After", wait))
            sleep_for = int(response.headers.get("Retry-After", wait))
            print(f"Rate limited. Waiting {sleep_for} seconds...")
            time.sleep(sleep_for)
            print(f"Rate limited. Waiting {sleep_for} seconds...")
            time.sleep(sleep_for)
            wait = min(wait * 2, 300)   # exponential back-off
            continue

        if response.status_code == 200:
            break

        print(f"Error {response.status_code} for {song} - {artist}")
        cache[key] = None
        return None

    try:
        track_id = response.json()['tracks']['items'][0]['id']
    except (KeyError, IndexError):
        track_id = None

    cache[key] = track_id
    with open(CACHE_FILE, "w") as f:
        json.dump(cache, f)

    time.sleep(6.0)   # ~10 req/min — safe zone (30-second rolling window)
    return track_id

unique_tracks = unique_tracks.copy()
unique_tracks['spotify_id'] = [
    search_track_id(row.song, row.artist)
    for row in tqdm(unique_tracks.itertuples(), total=len(unique_tracks))
]

  0%|          | 0/3938 [00:00<?, ?it/s]

Rate limited. Waiting 83042 seconds...

### NOTE: THIS POINT ONWARDS IS ALL THEORETICAL SINCE SPOTIFY BLOCKED ME FROM PULLING FOR A DAY MULTIPLE TIMES
This is meant to extract the features using these new song IDs and saving them to a new dataframe titled relevant_features.

In [ ]:
FEATURES_CACHE_FILE = "spotify_features_cache.json"

if os.path.exists(FEATURES_CACHE_FILE):
    with open(FEATURES_CACHE_FILE, "r") as f:
        features_cache = json.load(f)
else:
    features_cache = {}

def get_audio_features(track_id):
    if track_id is None:
        return None

    if track_id in features_cache:
        return features_cache[track_id]

    url  = f"https://api.spotify.com/v1/audio-features/{track_id}"
    wait = 2

    while True:
        response = requests.get(url, headers=headers)

        if response.status_code == 429:
            retry_after = int(response.headers.get("Retry-After", wait))
            sleep_for   = min(retry_after, 300)
            print(f"Rate limited. Waiting {sleep_for} seconds...")
            time.sleep(sleep_for)
            wait = min(wait * 2, 300)
            continue

        if response.status_code == 200:
            break

        print(f"Error {response.status_code} for track {track_id}")
        features_cache[track_id] = None
        return None

    features = response.json()
    features_cache[track_id] = features

    with open(FEATURES_CACHE_FILE, "w") as f:
        json.dump(features_cache, f)

    time.sleep(10.0)   # ~20 req/min — safe zone (30-second rolling window)
    return features

ids         = unique_tracks['spotify_id'].dropna().unique().tolist()
audio_feats = [get_audio_features(tid) for tid in tqdm(ids, desc="Audio features")]

relevant_features = pd.DataFrame([
    {"spotify_id": tid, "valence": f["valence"], "energy": f["energy"], "tempo": f["tempo"]}
    for tid, f in zip(ids, audio_feats)
    if f is not None
])

### Merging
Once the relevant_features is correctly built, we must merge it with our billboard_df dataframe. We aim to do this in 2 simple steps. First we attach the Spotify IDs back to the full billboard dataset. Then, we merge audio features using the Spotify ID.

In [ ]:
billboard_with_ids = billboard_df.merge(
    unique_tracks[['song', 'artist', 'spotify_id']],
    on=['song', 'artist'],
    how='left'
)

final_df = billboard_with_ids.merge(
    relevant_features,
    on='spotify_id',
    how='left'
)

final_df.head()

## Results

### Exploratory Data Analysis

Instructions: replace the words in this subsection with whatever words you need to setup and preview the EDA you're going to do.   

Please explicitly load the fully wrangled data you will use from `data/02-processed`.  This is a good idea rather than forcing people to re-run the data getting / wrangling cells above.  Sometimes it takes a long time to get / wrangle data compared to reloading the fixed up dataset.

Carry out whatever EDA you need to for your project in the code cells below.  Because every project will be different we can't really give you much of a template at this point. But please make sure you describe the what and why in text here as well as providing interpretation of results and context.

Please note that you should consider the use of python modules in your work.  Any code which gets called repeatedly should be modularized. So if you run the same pre-processing, analysis or visualiazation on different subsets of the data, then you should turn that into a function or class.  Put that function or class in a .py file that lives in `modules/`.  Import the module you made and use it to get your work done.  For reference see `get_raw()` which is inside `modules/get_data.py`.

#### Section 1 of EDA - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

#### Section 2 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Ethics


[![Deon badge](https://img.shields.io/badge/ethics%20checklist-deon-brightgreen.svg?style=popout-square)](http://deon.drivendata.org/)

### A. Data Collection
 - [X] **A.1 Informed consent**: If there are human subjects, have they given informed consent, where subjects affirmatively opt-in and have a clear understanding of the data uses to which they consent?

> Not Applicable: The project uses publicly available chart data and audio features. No human subjects or personal data (other than our own for the spotify IDs) are collected, so no consent is required. 

 - [x] **A.2 Collection bias**: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those?
> Billboard charts reflect only mainstream, comercially-focused music. This introduces bias, as independent artists and smaller genres are underrepresented. Our analysis shoud then focus on mainstream music to avoid overgeneralizing.

 - [x] **A.3 Limit PII exposure**: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?

> No personally identifiable information is collected. We ensure that no user-level streaming data or private accound information is collected or incorporated when getting the feature data from Spotify.

 - [ ] **A.4 Downstream bias mitigation**: Have we considered ways to enable testing downstream results for biased outcomes (e.g., collecting data on protected group status like race or gender)?

> Not applicable: the dataset contains no class attributes, so no need to test for this. 

### B. Data Storage
 - [x] **B.1 Data security**: Do we have a plan to protect and secure data (e.g., encryption at rest and in transit, access controls on internal users and third parties, access logs, and up-to-date software)?

> All data are public. API credentials are the main concern, but should be fine since they are environment variables.

 - [ ] **B.2 Right to be forgotten**: Do we have a mechanism through which an individual can request their personal information be removed?

> Not applicable: no personal data collected.

 - [ ] **B.3 Data retention plan**: Is there a schedule or plan to delete the data after it is no longer needed?

> Not applicable: dataset only contains pubic chart information and features. No actual sensitive data. 

### C. Analysis
 - [ ] **C.1 Missing perspectives**: Have we sought to address blindspots in the analysis through engagement with relevant stakeholders (e.g., checking assumptions and discussing implications with affected communities and subject matter experts)?

> The dataset excluded non-mainstream artists and genres, meaning our analysis does not capture the full diversity of musical experience across communities. So, we have to make clear that this is not a generalizable study.

 - [x] **C.2 Dataset bias**: Have we examined the data for possible sources of bias and taken steps to mitigate or address these biases (e.g., stereotype perpetuation, confirmation bias, imbalanced classes, or omitted confounding variables)?

> Billboard rankings are shaped by marketing, radio, and structural music industry inequalities. Findings may actually only reflect the behavior of the mainstream music industry rather than universal listeners.

 - [x] **C.3 Honest representation**: Are our visualizations, summary statistics, and reports designed to honestly represent the underlying data?

> Spotify's music features are only proxies, not direct measures of emotions. We must be careful about visualizations and interpretations to avoid implying causal or universal emotional conclusions.

 - [ ] **C.4 Privacy in analysis**: Have we ensured that data with PII are not used or displayed unless necessary for the analysis?

> Not applicable: Same reason as PII- it is not used.

 - [ ] **C.5 Auditability**: Is the process of generating the analysis well documented and reproducible if we discover issues in the future?

> The analysis is reproducible, but our API still needs work with its rate-limits. 

### D. Modeling
 - [x] **D.1 Proxy discrimination**: Have we ensured that the model does not rely on variables or proxies for variables that are unfairly discriminatory?

> The model uses only musical features that contain no sensitive attributes, reducing proxy risk, but might still only capture mainstream musical industry movement instead.

 - [ ] **D.2 Fairness across groups**: Have we tested model results for fairness with respect to different affected groups (e.g., tested for disparate error rates)?

> Not applicable: no human groups.

 - [ ] **D.3 Metric selection**: Have we considered the effects of optimizing for our defined metrics and considered additional metrics?

> Metrics reflect musical characteristics only. The emotional aspect is treated more cautiously.

 - [ ] **D.4 Explainability**: Can we explain in understandable terms a decision the model made in cases where a justification is needed?

> The analysis should be descriptive rather than predictive, so explainability concerns are minimal.

 - [x] **D.5 Communicate limitations**: Have we communicated the shortcomings, limitations, and biases of the model to relevant stakeholders in ways that can be generally understood?

> Limitations related to dataset bias, feature interpretations, and representativeness must clearly be comminicated to avoid overstating findings. 

### E. Deployment
 - [ ] **E.1 Monitoring and evaluation**: Do we have a clear plan to monitor the model and its impacts after it is deployed (e.g., performance monitoring, regular audit of sample predictions, human review of high-stakes decisions, reviewing downstream impacts of errors or low-confidence decisions, testing for concept drift)?

> N/A: no deployed system or decision making tool used.

 - [ ] **E.2 Redress**: Have we discussed with our organization a plan for response if users are harmed by the results (e.g., how does the data science team evaluate these cases and update analysis and models to prevent future harm)?

> N/A: the project does not give outputs that could cause harm.

 - [ ] **E.3 Roll back**: Is there a way to turn off or roll back the model in production if necessary?

> N/A: no production system exists, and/or we can force stop indefinite running code using datahub kernel stopper.

 - [ ] **E.4 Unintended use**: Have we taken steps to identify and prevent unintended uses and abuse of the model and do we have a plan to monitor these once the model is deployed?

> The analysis is academic and descriptive, so nothing can really be misused apart from the findings, which is something already covered by other points.

## Team Expectations

* *We will do our best to respond to any and all communication within a reasonable time frame (within roughly half a day)*
* *On important days (e.g. submission days and the day before submission is due) we will do our best to respond more readily (within roughly 2-3 hours)*
* *Any disagreements on the direction of the project, or of any of its individual components, will be resolved by a team vote. By agreeing to write your name in the author's section, you are agreeing to this clause.*
* *We must agree to not speak down on anyone, regardless of how trivial a question may seem to you. We will be helpful and respectful.*
* *We will contribute to every team meeting by proposing ideas, regardless of if they're fully fleshed out or not. Input from every member is valued equally.*
* *HONOR DEADLINES!! When things slip (and they will), and if you **NEED** to focus on other work or your job, communicate that clearly to other members. If deadlines become unrealistic, we will be respectful and do our best to cover for the work you need to put down.*
* *Miscommunications will happen, do not assume the worst of the other. We will resolve conflicts collaboratively and work towards solutions that respect everyone's perspective.*
* *For major code changes/document updates, please use a branch and let everyone know ahead of time before you commit and push to master. Make an announcement on the Discord and/or group text to make sure everyone is aware and can cleanly address any potential conflicts.*
* *Respect Each other's time and boundaries. We acknowledge that we all have responsibilies outside of this project, so it cannot be expected of someone to fulfill a last minute demand unless they consent.*
* *This list is neither extensive nor exauhstive. As we work on this project, new expectations/erratums/or removals of an expectation can be proposed, discussed, and added as we see fit.*

## Project Timeline Proposal

| Meeting Date | Meeting Time | Completed Before Meeting | Discuss at Meeting |
|---|---|---|---|
| 1/28 | 3:50 PM | Read COGS 108 project expectations; brainstorm possible topics and research questions | Determine communication methods; narrow topic ideas; discuss seasonal music trends and possible variables |
| 2/2 | 3:30 PM | Conduct background research on seasonality, mood, and music features | Finalize research question; discuss hypothesis; identify possible datasets (Billboard +  features); begin proposal drafting |
| 2/12 | 3:00 PM | Upload and organize Billboard Top 100 dataset| Review dataset quality; verify seasonal labels; discuss data cleaning challenges; assign EDA responsibilities |
| 2/17 | 7:00 PM | Complete dataset cleaning and preprocessing; complete Spotify API | Review exploratory data analysis; identify seasonal patterns; finalize statistical analysis plan |
| 2/24 | 7:00 PM | Review exploratory data analysis; identify seasonal patters; finalize analysis plan | Conduct statistical tests comparing valence, tempo, and energy across seasons; begin drafting results; Interpret statistical findings; discuss limitations and ethical considerations; assign writing sections |
| 2/29 | 3:00 PM | Draft full project report; finalize visualizations and code documentation | Peer edit project; ensure reproducibility; finalize submission materials |
| Final Submission | Before Deadline | Complete final revisions and group project survey | Submit final project and all required materials |